import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const netflixSans = localFont({
  src: [
    {
      path: "../public/font/NetflixSans_W_Th.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/font/NetflixSans_W_Lt.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/font/NetflixSans_W_Rg.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/NetflixSans_W_Bd.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/font/NetflixSans_W_Blk.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-netflix-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={netflixSans.variable}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
