export type MovieOrSeries = {
  title: string;
  genres: string[];
  thumbnailUrl: string;
  previewUrl: string;
  progressWatched: number;
};

export type Category = {
  id: string;
  title: string;
  items: MovieOrSeries[];
};

export const moviesAndSeries: { [key: string]: MovieOrSeries } = {
  absentia: {
    title: "Absentia",
    genres: ["Thriller", "Misterio", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Absentia.png",
    previewUrl: "/mp4/previews/Absentia.mp4",
    progressWatched: 15,
  },
  ahoraMeVes2: {
    title: "Ahora me ves 2",
    genres: ["Acción", "Crimen", "Magia", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Ahora me ves 2.png",
    previewUrl: "/mp4/previews/Ahora me ves 2.mp4",
    progressWatched: 10,
  },
  ahoraMeVes: {
    title: "Ahora me ves...",
    genres: ["Acción", "Crimen", "Magia", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Ahora me ves....png",
    previewUrl: "/mp4/previews/Ahora me ves....mp4",
    progressWatched: 90,
  },
  alertaExtrema: {
    title: "Alerta extrema",
    genres: ["Acción", "Thriller", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Alerta extrema.png",
    previewUrl: "/mp4/previews/Alerta extrema.mp4",
    progressWatched: 20,
  },
  animal: {
    title: "Animal",
    genres: ["Drama", "Thriller", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Animal.png",
    previewUrl: "/mp4/previews/Animal.mp4",
    progressWatched: 0,
  },
  arcane: {
    title: "Arcane",
    genres: ["Animación", "Acción", "Fantástico", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Arcane.png",
    previewUrl: "/mp4/previews/Arcane.mp4",
    progressWatched: 45,
  },
  bellezaVerdadera: {
    title: "Belleza verdadera",
    genres: ["Romance", "Juvenil", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Belleza verdadera.png",
    previewUrl: "/mp4/previews/Belleza verdadera.mp4",
    progressWatched: 5,
  },
  bigMouth: {
    title: "Big Mouth",
    genres: ["Animación", "Comedia", "Adultos", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Big Mouth.png",
    previewUrl: "/mp4/previews/Big Mouth.mp4",
    progressWatched: 0,
  },
  bojackHorseman: {
    title: "BoJack Horseman",
    genres: ["Animación", "Drama", "Comedia", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/BoJack Horseman.png",
    previewUrl: "/mp4/previews/BoJack Horseman.mp4",
    progressWatched: 65,
  },
  cafeConAromaDeMujer: {
    title: "Café con aroma de mujer",
    genres: ["Romance", "Drama", "Novela"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Café con aroma de mujer.png",
    previewUrl: "/mp4/previews/Café con aroma de mujer.mp4",
    progressWatched: 15,
  },
  cantaConLasGuerrerasKpop: {
    title: "Canta con las guerreras k-pop",
    genres: ["Música", "Documental", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Canta con las guerreras k-pop.png",
    previewUrl: "/mp4/previews/Canta con las guerreras k-pop.mp4",
    progressWatched: 25,
  },
  caramelo: {
    title: "Caramelo",
    genres: ["Romance", "Comedia", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Caramelo.png",
    previewUrl: "/mp4/previews/Caramelo.mp4",
    progressWatched: 10,
  },
  conCMayuscula: {
    title: "Con C mayúscula",
    genres: ["Drama", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Con C mayúscula.png",
    previewUrl: "/mp4/previews/Con C mayúscula.mp4",
    progressWatched: 0,
  },
  cuestionDeJusticia: {
    title: "Cuestión de justicia",
    genres: ["Drama", "Legal", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Cuestión de justicia.png",
    previewUrl: "/mp4/previews/Cuestión de justicia.mp4",
    progressWatched: 10,
  },
  deVueltaALaAccion: {
    title: "De vuelta a la acción",
    genres: ["Acción", "Comedia", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/De vuelta a la acción.png",
    previewUrl: "/mp4/previews/De vuelta a la acción.mp4",
    progressWatched: 5,
  },
  devilMayCry: {
    title: "Devil May Cry",
    genres: ["Animación", "Acción", "Fantasía", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Devil May Cry.png",
    previewUrl: "/mp4/previews/Devil May Cry.mp4",
    progressWatched: 0,
  },
  elCucoDeCristal: {
    title: "El cuco de cristal",
    genres: ["Thriller", "Suspenso", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El cuco de cristal.png",
    previewUrl: "/mp4/previews/El cuco de cristal.mp4",
    progressWatched: 0,
  },
  elElixirDeLaInmortalidad: {
    title: "El elixir de la inmortalidad",
    genres: ["Thriller", "Misterio", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El elixir de la inmortalidad.png",
    previewUrl: "/mp4/previews/El elixir de la inmortalidad.mp4",
    progressWatched: 5,
  },
  elHotelEmbrujado: {
    title: "El hotel embrujado",
    genres: ["Familiar", "Fantasía", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El hotel embrujado.png",
    previewUrl: "/mp4/previews/El hotel embrujado.mp4",
    progressWatched: 0,
  },
  elJovenSheldon: {
    title: "El joven Sheldon",
    genres: ["Comedia", "Familiar", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El joven Sheldon.png",
    previewUrl: "/mp4/previews/El joven Sheldon.mp4",
    progressWatched: 5,
  },
  elJuegoDelCalamar: {
    title: "El juego del calamar",
    genres: ["Thriller", "Supervivencia", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El juego del calamar.png",
    previewUrl: "/mp4/previews/El juego del calamar.mp4",
    progressWatched: 80,
  },
  elUltimoSamuraiEnPie: {
    title: "El último samurái en pie",
    genres: ["Acción", "Bélico", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/El último samurái en pie.png",
    previewUrl: "",
    progressWatched: 0,
  },
  focus: {
    title: "Focus",
    genres: ["Comedia", "Crimen", "Romance", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Focus.png",
    previewUrl: "/mp4/previews/Focus.mp4",
    progressWatched: 35,
  },
  gladiador2: {
    title: "Gladiador II",
    genres: ["Acción", "Drama", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Gladiador II.png",
    previewUrl: "/mp4/previews/Gladiador II.mp4",
    progressWatched: 0,
  },
  godzillaYKongElNuevoImperio: {
    title: "Godzilla y Kong: El nuevo imperio",
    genres: ["Acción", "Monstruos", "Ciencia ficción", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Godzilla y Kong- El nuevo imperio.png",
    previewUrl: "/mp4/previews/Godzilla y Kong- El nuevo imperio.mp4",
    progressWatched: 15,
  },
  infiniteMovie: {
    title: "Infinite",
    genres: ["Acción", "Ciencia ficción", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Infinite.png",
    previewUrl: "/mp4/previews/Infinite.mp4",
    progressWatched: 0,
  },
  johnWick4: {
    title: "John Wick 4",
    genres: ["Acción", "Crimen", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/John Wick 4.png",
    previewUrl: "/mp4/previews/John Wick 4.mp4",
    progressWatched: 60,
  },
  juegoDeArmas: {
    title: "Juego de armas",
    genres: ["Comedia", "Crimen", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Juego de armas.png",
    previewUrl: "/mp4/previews/Juego de armas.mp4",
    progressWatched: 15,
  },
  kingTheLand: {
    title: "King the Land",
    genres: ["Romance", "Comedia", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/King the Land.png",
    previewUrl: "/mp4/previews/King the Land.mp4",
    progressWatched: 30,
  },
  krakensYSirenasConoceALosGillman: {
    title: "Krakens y sirenas: Conoce a los Gillman",
    genres: ["Animación", "Aventura", "Familiar", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Krakens y sirenas- Conoce a los Gillman.png",
    previewUrl: "/mp4/previews/Krakens y sirenas- Conoce a los Gillman.mp4",
    progressWatched: 5,
  },
  lasGuerrerasKpop: {
    title: "Las guerreras k-pop",
    genres: ["Música", "Juvenil", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Las guerreras k-pop.png",
    previewUrl: "/mp4/previews/Las guerreras k-pop.mp4",
    progressWatched: 0,
  },
  losElegidos: {
    title: "Los elegidos",
    genres: ["Drama", "Suspenso", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Los elegidos.png",
    previewUrl: "/mp4/previews/Los elegidos.mp4",
    progressWatched: 0,
  },
  pequenosDetalles: {
    title: "Pequeños detalles",
    genres: ["Crimen", "Thriller", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Pequeños detalles.png",
    previewUrl: "/mp4/previews/Pequeños detalles.mp4",
    progressWatched: 25,
  },
  rapidosYFuriososX: {
    title: "Rápidos y furiosos X",
    genres: ["Acción", "Carreras", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Rápidos y furiosos X.png",
    previewUrl: "/mp4/previews/Rápidos y furiosos X.mp4",
    progressWatched: 70,
  },
  reclutas: {
    title: "Reclutas",
    genres: ["Drama", "Acción", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Reclutas.png",
    previewUrl: "/mp4/previews/Reclutas.mp4",
    progressWatched: 50,
  },
  rickYMorty: {
    title: "Rick y Morty",
    genres: ["Animación", "Ciencia ficción", "Comedia", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Rick y Morty.png",
    previewUrl: "/mp4/previews/Rick y Morty.mp4",
    progressWatched: 55,
  },
  shameless: {
    title: "Shameless",
    genres: ["Comedia", "Drama", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Shameless.png",
    previewUrl: "/mp4/previews/Shameless.mp4",
    progressWatched: 10,
  },
  sonic3LaPelicula: {
    title: "Sonic 3: La película",
    genres: ["Aventura", "Acción", "Familiar", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Sonic 3- La película.png",
    previewUrl: "/mp4/previews/Sonic 3- La película.mp4",
    progressWatched: 20,
  },
  spiderManNoWayHome: {
    title: "Spider-Man: No Way Home",
    genres: ["Acción", "Superhéroes", "Aventura", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Spider-Man- No Way Home.png",
    previewUrl: "/mp4/previews/Spider-Man- No Way Home.mp4",
    progressWatched: 85,
  },
  suits: {
    title: "Suits",
    genres: ["Drama", "Legal", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Suits.png",
    previewUrl: "/mp4/previews/Suits.mp4",
    progressWatched: 5,
  },
  theRookie: {
    title: "The Rookie",
    genres: ["Policial", "Drama", "Serie"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/The Rookie.png",
    previewUrl: "/mp4/previews/The Rookie.mp4",
    progressWatched: 10,
  },
  unBesoConChispa: {
    title: "Un beso con chispa",
    genres: ["Romance", "Comedia", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Un beso con chispa.png",
    previewUrl: "/mp4/previews/Un beso con chispa.mp4",
    progressWatched: 0,
  },
  unGolpeConEstilo: {
    title: "Un golpe con estilo",
    genres: ["Comedia", "Crimen", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Un golpe con estilo.png",
    previewUrl: "/mp4/previews/Un golpe con estilo.mp4",
    progressWatched: 0,
  },
  unaCasaLlenaDeDinamita: {
    title: "Una casa llena de dinamita",
    genres: ["Comedia", "Acción", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Una casa llena de dinamita.png",
    previewUrl: "/mp4/previews/Una casa llena de dinamita.mp4",
    progressWatched: 5,
  },
  unchartedMovie: {
    title: "Uncharted",
    genres: ["Acción", "Aventura", "Película"],
    thumbnailUrl: "/imgs/movie-series-thumbnails/Uncharted.png",
    previewUrl: "/mp4/previews/Uncharted.mp4",
    progressWatched: 5,
  },
};

const allItems: MovieOrSeries[] = Object.values(moviesAndSeries);

export const movieSeriesCategories: Category[] = [
  {
    id: "solo-en-netflix",
    title: "Solo en Netflix",
    items: [
      moviesAndSeries.elJuegoDelCalamar,
      moviesAndSeries.arcane,
      moviesAndSeries.bigMouth,
      moviesAndSeries.bojackHorseman,
      moviesAndSeries.rickYMorty,
      moviesAndSeries.devilMayCry,
    ],
  },
  {
    id: "recomendado-para-ti",
    title: "Recomendado solo para ti",
    items: [
      moviesAndSeries.reclutas,
      moviesAndSeries.suits,
      moviesAndSeries.kingTheLand,
      moviesAndSeries.cafeConAromaDeMujer,
      moviesAndSeries.losElegidos,
      moviesAndSeries.bellezaVerdadera,
      moviesAndSeries.unBesoConChispa,
      moviesAndSeries.cantaConLasGuerrerasKpop,
      moviesAndSeries.lasGuerrerasKpop,
      moviesAndSeries.elJovenSheldon,
      moviesAndSeries.theRookie,
      moviesAndSeries.absentia,
    ],
  },
  {
    id: "series-para-maraton",
    title: "Series para maratonear",
    items: [
      moviesAndSeries.shameless,
      moviesAndSeries.rickYMorty,
      moviesAndSeries.elJovenSheldon,
      moviesAndSeries.absentia,
      moviesAndSeries.theRookie,
      moviesAndSeries.suits,
    ],
  },
  {
    id: "comedias-de-hollywood",
    title: "Comedias de Hollywood",
    items: [
      moviesAndSeries.unGolpeConEstilo,
      moviesAndSeries.focus,
      moviesAndSeries.ahoraMeVes2,
      moviesAndSeries.ahoraMeVes,
      moviesAndSeries.juegoDeArmas,
      moviesAndSeries.unaCasaLlenaDeDinamita,
      moviesAndSeries.deVueltaALaAccion,
      moviesAndSeries.caramelo,
      moviesAndSeries.conCMayuscula,
      moviesAndSeries.unBesoConChispa,
      moviesAndSeries.elHotelEmbrujado,
      moviesAndSeries.krakensYSirenasConoceALosGillman,
    ],
  },
  {
    id: "accion-y-adrenalina",
    title: "Acción y adrenalina",
    items: [
      moviesAndSeries.rapidosYFuriososX,
      moviesAndSeries.sonic3LaPelicula,
      moviesAndSeries.spiderManNoWayHome,
      moviesAndSeries.godzillaYKongElNuevoImperio,
      moviesAndSeries.johnWick4,
      moviesAndSeries.unchartedMovie,
      moviesAndSeries.gladiador2,
      moviesAndSeries.infiniteMovie,
      moviesAndSeries.devilMayCry,
      moviesAndSeries.alertaExtrema,
      moviesAndSeries.elUltimoSamuraiEnPie,
      moviesAndSeries.animal,
    ],
  },
  {
    id: "todo-el-catalogo",
    title: "Explora todo el catálogo",
    items: allItems,
  },
];


